# Generated by Django 5.2.4 on 2025-07-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg'), ('shake', 'Shake'), ('drink', 'Drink')], default='veg', max_length=10),
        ),
    ]
